apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-proxy.fullname" . }}
  labels:
    {{- include "s3-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  S3PROXY_AUTHORIZATION: {{ .Values.conf.S3PROXY_AUTHORIZATION }}
  S3PROXY_ENDPOINT: {{ .Values.conf.S3PROXY_ENDPOINT }}
  S3PROXY_IDENTITY: {{ .Values.conf.S3PROXY_IDENTITY }}
  S3PROXY_CREDENTIAL: {{ .Values.conf.S3PROXY_CREDENTIAL }}
  S3PROXY_CORS_ALLOW_ALL: {{ .Values.conf.S3PROXY_CORS_ALLOW_ALL }}
  S3PROXY_CORS_ALLOW_ORIGINS: {{ .Values.conf.S3PROXY_CORS_ALLOW_ORIGINS }}
  S3PROXY_CORS_ALLOW_METHODS: {{ .Values.conf.S3PROXY_CORS_ALLOW_METHODS }}
  S3PROXY_CORS_ALLOW_HEADERS: {{ .Values.conf.S3PROXY_CORS_ALLOW_HEADERS }}
  S3PROXY_IGNORE_UNKNOWN_HEADERS: {{ .Values.conf.S3PROXY_IGNORE_UNKNOWN_HEADERS }}
  JCLOUDS_PROVIDER: {{ .Values.conf.JCLOUDS_PROVIDER }}
  JCLOUDS_ENDPOINT: {{ .Values.conf.JCLOUDS_ENDPOINT }}
  JCLOUDS_REGION: {{ .Values.conf.JCLOUDS_REGION }}
  JCLOUDS_REGIONS: {{ .Values.conf.JCLOUDS_REGIONS }}
  JCLOUDS_IDENTITY: {{ .Values.conf.JCLOUDS_IDENTITY }}
  JCLOUDS_CREDENTIAL: {{ .Values.conf.JCLOUDS_CREDENTIAL }}
  JCLOUDS_KEYSTONE_VERSION: {{ .Values.conf.JCLOUDS_KEYSTONE_VERSION }}
  JCLOUDS_KEYSTONE_SCOPE: {{ .Values.conf.JCLOUDS_KEYSTONE_SCOPE }}
  JCLOUDS_KEYSTONE_PROJECT_DOMAIN_NAME: {{ .Values.conf.JCLOUDS_KEYSTONE_PROJECT_DOMAIN_NAME }}
